#!/bin/bash

echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo;
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0;31m)';
echo -n -e '\e[0;31m\';
echo -n -e '\e[0;31m,';
echo -n -e '\e[0;31m,';
echo -n -e '\e[0;31m,';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo;
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m/';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m@';
echo -n -e '\e[0m@';
echo;
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m/';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[1;37mo';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m@';
echo;
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m/';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m)';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m@';
echo;
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m\';
echo -n -e '\e[0m°';
echo -n -e '\e[0m ';
echo -n -e '\e[0m/';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m/';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m@';
echo;
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m/';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m@';
echo;
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m/';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m@';
echo;
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m/';
echo -n -e '\e[0m_';
echo -n -e '\e[0m_';
echo -n -e '\e[0m_';
echo -n -e '\e[0m_';
echo -n -e '\e[0m_';
echo -n -e '\e[0m_';
echo -n -e '\e[0m@';
echo;
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[1;33m(';
echo -n -e '\e[1;33m_';
echo -n -e '\e[1;33m_';
echo -n -e '\e[1;33m_';
echo -n -e '\e[1;33m_';
echo -n -e '\e[1;33m_';
echo -n -e '\e[1;33m_';
echo -n -e '\e[1;33m_';
echo -n -e '\e[1;33m)';
echo;
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[0m ';
echo -n -e '\e[1;33m(';
echo -n -e '\e[1;33m_';
echo -n -e '\e[1;33m_';
echo -n -e '\e[1;33m_';
echo -n -e '\e[1;33m_';
echo -n -e '\e[1;33m_';
echo -n -e '\e[1;33m_';
echo -n -e '\e[1;33m_';
echo -n -e '\e[1;33m_';
echo -n -e '\e[1;33m_';
echo -n -e '\e[1;33m)';
echo;
